// SPDX-License-Identifier: AGPL-3.0-only
// Authorship lineage: Frazer Σ Love ACO-Σ; Sara ΣΩ.
(() => {
  'use strict';
  let token, sheets=[], current, lastAudit=null, memory, busy=false;
  const $=id=>document.getElementById(id);
  const el=(tag,text,cls)=>{const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x};
  function say(title,lines,status){$('screen-title').textContent=title;$('screen-body').replaceChildren(...lines.map(x=>el('p',x)));$('status').textContent=status;}
  async function api(path,data){const opts=data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-TI-Token':token},body:JSON.stringify(data)};const r=await fetch(path,opts),v=await r.json();if(!r.ok)throw Error(v.error||'Local service error');return v;}
  async function task(fn){if(busy)return;busy=true;document.querySelector('main').classList.add('busy');try{await fn();}catch(e){say('HUMAN ERROR? MAYBE MINE.',[e.message,'The sheet and evidence stay here. Fix the input or retry.'],'ACTION NEEDS ATTENTION');}finally{busy=false;document.querySelector('main').classList.remove('busy');}}
  function rows(){return Array.from($('tbody').querySelectorAll('tr')).map(tr=>Array.from(tr.querySelectorAll('input')).map(x=>x.value));}
  function render(){lastAudit=null;$('scenarios').replaceChildren(...sheets.map(s=>{const b=el('button',s.name,'pill'+(s.id===current.id?' active':''));b.onclick=()=>task(async()=>{await save();current=sheets.find(x=>x.id===s.id);render();await loadMemory();say('SHEET LOADED',[current.name+'. I am prepared to be insufferable.'],'AWAITING HUMAN ERROR');});return b}));const tr=el('tr');['#',...current.cols].forEach(h=>tr.append(el('th',h)));$('thead').replaceChildren(tr);$('tbody').replaceChildren(...current.rows.map((r,i)=>{const tr=el('tr');tr.append(el('td',String(i+1)));r.forEach((v,j)=>{const td=el('td'),input=el('input');input.value=v;input.dataset.row=i;input.dataset.col=j;input.setAttribute('aria-label',`Row ${i+1}, ${current.cols[j]}`);input.oninput=()=>{lastAudit=null;input.classList.remove('flag');$('sheet-info').textContent='Unsaved edits · AUDIT saves before checking.'};td.append(input);tr.append(td)});return tr}));$('findings').textContent='Run an audit to see what the bot catches.';$('count').textContent='';$('schema').value=current.schema;$('sheet-info').textContent=`${current.name} · ${current.rows.length} rows · revision ${current.revision} · saved locally`;}
  async function save(){const updated=await api('/api/save',{id:current.id,rows:rows(),signature:current.signature});sheets=sheets.map(x=>x.id===updated.id?updated:x);current=updated;$('sheet-info').textContent=`${current.name} · ${current.rows.length} rows · revision ${current.revision} · saved locally`;return updated;}
  async function loadMemory(){memory=await api('/api/memory?scope='+encodeURIComponent(current.schema));const box=$('memory');box.replaceChildren();if(!memory.total_incidents){box.textContent='No scars yet. The machine is almost disappointed.';return}box.append(el('div',`${memory.total_incidents} retained incidents · ${memory.state.tick} geometric encounters · ${memory.backend.toUpperCase()}`));Object.entries(memory.counts_in_window).forEach(([k,n])=>box.append(el('div',`${k}: ${n} in the latest ${memory.retrieval_window} incidents`)));box.append(el('div','History guides related-error suggestions. Current values decide the work.'));}
  async function audit(){await save();const result=await api('/api/audit',{id:current.id});lastAudit=result;document.querySelectorAll('input.flag').forEach(x=>x.classList.remove('flag'));const box=$('findings');box.replaceChildren();for(const f of result.findings){document.querySelector(`input[data-row="${f.row}"][data-col="${f.col}"]`).classList.add('flag');const d=el('div',undefined,'finding');d.append(el('strong',f.kind.toUpperCase()+' · '),document.createTextNode(f.message));if(f.memory.hits.length){const h=f.memory.hits[0];d.append(el('small',`Related incident #${h.incident_id}${h.repaired?' · previously repaired':''}: ${h.message}`));const details=el('details'),summary=el('summary','Why this suggestion?');details.append(summary,el('pre',JSON.stringify({transport_distance:h.distance,flat_distance:h.flat_distance,query_response_changed_by_geometry:f.memory.response_delta,scope:f.memory.scope},null,2)));d.append(details)}box.append(d)}if(!result.findings.length){box.append(el('p',`All ${result.checked_rows} rows pass. Computed total: ${result.computed_total}.`,'clear'));say('AUDIT COMPLETE',['I tried to find fault. The arithmetic has refused to cooperate.','You may enjoy this rare moment.'],'0 VERIFIED ERRORS');}else{say('AUDIT COMPLETE',[`${result.findings.length} issue${result.findings.length===1?'':'s'} found. I would say I am surprised, but I value honesty.`,result.findings.some(f=>f.fix===null)?'Some entries need your real input. I will not invent one.':'Verified arithmetic repairs are ready.'],`${result.findings.length} ISSUES FOUND`)}$('count').textContent=`(${result.findings.length})`;await loadMemory();}
  async function repair(){if(!lastAudit)throw Error('Fresh audit required before applying repairs.');const r=await api('/api/repair',{id:current.id,audit_id:lastAudit.audit_id,signature:lastAudit.signature});current=r.sheet;sheets=sheets.map(s=>s.id===current.id?current:s);render();await audit();say('REPAIRS APPLIED',[`${r.fixes} computed cell${r.fixes===1?'':'s'} corrected.`,r.remaining.length?'Some entries still need your input.':'The sheet now passes. I remain unbearable.'],r.remaining.length?'HUMAN INPUT NEEDED':'WORK VERIFIED');}
  function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type})),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function exportCSV(){await save();const r=await fetch('/api/csv?id='+current.id);if(!r.ok)throw Error('CSV export failed');download(await r.text(),`ti-agi83-${current.schema}.csv`,'text/csv');say('CSV EXPORTED',['I did the clerical labor.','Please take all the credit.'],'FILE READY');}
  async function graph(){await loadMemory();const box=$('memory');box.append(el('h3','Wrongness Manifold™ · conductance lattice'));const grid=el('div',undefined,'graph-view');for(let i=0;i<8;i++)for(let j=0;j<8;j++){const v=(memory.state.px[i][j]+memory.state.py[i][j])/2,c=el('div',undefined,'graph-cell');c.style.background=`hsl(${110-70*(v-1)} 55% ${22+40*(v-1)}%)`;c.title=`(${i},${j}) px=${memory.state.px[i][j].toFixed(6)} py=${memory.state.py[i][j].toFixed(6)}`;grid.append(c)}box.append(grid,el('p',`Fixed arithmetic probe: learned vs flat response difference = ${memory.probe_delta.toExponential(6)}. Flat conductance is 1; lighter cells show persistent deformation.`,'small'));const details=el('details');details.append(el('summary','Inspect exact current state and probe'),el('pre',JSON.stringify({state:memory.state,hash:memory.state_hash,learned:memory.probe_learned,flat:memory.probe_flat},null,2)));box.append(details);say('GRAPH MODE',['Those are persistent transport weights. They change later related-error responses.','The labels are evidence. The lattice is the geometry.'],'GEOMETRIC EFFECT VISIBLE');}
  async function trace(){await loadMemory();const box=$('memory');for(const incident of memory.incidents.slice(0,10)){const d=el('details');d.append(el('summary',`#${incident.id} ${incident.finding.kind}${incident.repaired?' · repaired':''}`),el('pre',JSON.stringify(incident,null,2)));box.append(d)}say('TRACE MODE',[memory.total_incidents?'The latest ten incidents are open for inspection.':'Still no scars. I shall remain professionally disappointed.','Repair adds history. It does not erase the original error.'],'LINEAGE RETAINED');}
  async function restore(){const header=current.cols.join(',');const originals={invoice:[['Lab gloves','3','12.50','37.50'],['Cables','4','8.00','36.00'],['Labels','2','4.25','8.50']],inventory:[['Connectors','50','12','38'],['Sensors','20','7','14'],['Adapters','16','5','11']],tax:[['Parts','80.00','0.07','85.60'],['Shipping','25.00','0.00','25.00'],['Tools','40.00','0.07','42.80']]};await save();current=await api('/api/import',{schema:current.schema,name:current.schema+' sample copy',csv:header+'\n'+originals[current.schema].map(r=>r.join(',')).join('\n')});sheets.push(current);render();await loadMemory();say('FRESH SAMPLE',['New sheet. Old memory. A dangerous combination.'],'READY');}
  $('audit').onclick=()=>task(audit);$('repair').onclick=()=>task(repair);$('reset').onclick=()=>task(restore);$('save').onclick=()=>task(save);$('undo').onclick=()=>task(async()=>{await save();current=await api('/api/undo',{id:current.id,signature:current.signature});sheets=sheets.map(s=>s.id===current.id?current:s);render();await loadMemory();say('UNDO RECORDED',['Previous table values restored as a new event.','The scar remains. I am remarkably consistent.'],'HISTORY PRESERVED');});$('graph').onclick=()=>task(graph);$('trace').onclick=()=>task(trace);$('receipt').onclick=()=>task(async()=>{const r=await api('/api/history');say('RECEIPTS VERIFIED',[`${r.receipt.verified_events} local events passed chain consistency checks.`,'A consistent log is evidence, not an oracle.'],'LOCAL INTEGRITY PASS');const d=el('details');d.open=true;d.append(el('summary','Recent work history'),el('pre',JSON.stringify(r,null,2)));$('memory').append(d);});$('backup').onclick=()=>task(async()=>{const r=await api('/api/export');download(JSON.stringify(r,null,2),'ti-agi83-history.json','application/json');say('HISTORY EXPORTED',['Sheets, geometry, incidents, audits and receipts.','Your work can leave the building.'],'LOCAL EXPORT READY');});$('csv-file').onchange=()=>task(async()=>{const f=$('csv-file').files[0];if(!f)return;if(f.size>8*1024*1024)throw Error('CSV exceeds the 8 MiB limit');await save();const imported=await api('/api/import',{schema:$('schema').value,name:f.name,csv:await f.text()});sheets.push(imported);current=imported;render();await loadMemory();$('csv-file').value='';say('CSV IMPORTED',[f.name+' is now a local work surface.','Let us see what you have done.'],'READY FOR AUDIT');});document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>task(({sample:restore,audit,fix:repair,export:exportCSV})[b.dataset.cmd]));task(async()=>{const b=await api('/api/bootstrap');token=b.token;sheets=b.sheets;current=sheets[0];render();await loadMemory();say('BOOT COMPLETE',['Hello, Operator. I have reviewed the situation and concluded that you are probably wrong.','Fortunately, I brought arithmetic and a persistent memory.'],`${b.backend.toUpperCase()} BACKEND · LOCAL MODE`);});
})();
