// SPDX-License-Identifier: AGPL-3.0-only
// Authorship lineage: Frazer Σ Love ACO-Σ; Sara ΣΩ.
'use strict';
window.TIArcade={mount({api,say,saveWork,run}){
  const $=id=>document.getElementById(id),canvas=$('game-canvas'),ctx=canvas.getContext('2d');
  const names={snake:'Snake',blocks:'Falling Blocks',pong:'Pong'};
  const instructions={snake:'Arrow keys / WASD steer. Eat pixels. Avoid walls and yourself.',blocks:'Left/right move. Up rotates. Down soft-drops. Space hard-drops.',pong:'Up/down / W/S move your paddle. First to five wins. Your record is the longest rally.'};
  let kind='snake',model=TIArcadeEngine.create(kind),mode='work',started=false,playing=false,timer=null,scoreId=null,scorePending=false,scoreSaved=false,stats={};
  const held=new Set();
  function records(value){stats=value.games;const s=stats[kind];$('game-best').textContent=s?`Your best: ${s.best===null?'—':s.best} · ${s.plays} completed game${s.plays===1?'':'s'} saved locally`:'No saved games yet.';}
  function stop(redraw=true){playing=false;held.clear();clearTimeout(timer);timer=null;$('game-pause').textContent='Resume game';if(redraw)draw();}
  function update(){const summary=kind==='pong'?`YOU ${model.playerPoints} · CPU ${model.cpuPoints} · Rally ${model.rally} · Best rally ${model.score}`:`Score ${model.score}${kind==='blocks'?` · Lines ${model.lines} · Level ${model.level}`:''}`;$('game-score').textContent=summary;$('game-state').textContent=model.over?(scoreSaved?'GAME OVER · SCORE SAVED':scorePending?'GAME OVER · SAVING SCORE':'GAME OVER · SCORE NOT SAVED'):playing?'PLAYING':started?'PAUSED':'READY';$('game-pause').disabled=!started||model.over;$('game-retry').hidden=!model.over||scorePending||scoreSaved;}
  function draw(){ctx.imageSmoothingEnabled=false;ctx.fillStyle='#b7cd95';ctx.fillRect(0,0,96,64);ctx.fillStyle='#243d27';if(kind==='snake'){model.snake.forEach(p=>ctx.fillRect(p.x*4,p.y*4,3,3));if(model.food){ctx.strokeRect(model.food.x*4+.5,model.food.y*4+.5,2,2);}}else if(kind==='blocks'){ctx.strokeRect(27.5,.5,40,63);const cell=(x,y)=>ctx.fillRect(28+x*4,y*4,3,3);model.board.forEach((row,y)=>row.forEach((v,x)=>{if(v)cell(x,y)}));if(!model.over)model.piece.forEach((row,y)=>row.forEach((v,x)=>{if(v)cell(model.x+x,model.y+y)}));ctx.font='5px monospace';ctx.fillText('NEXT',73,7);model.next.forEach((row,y)=>row.forEach((v,x)=>{if(v)ctx.fillRect(73+x*4,12+y*4,3,3)}));ctx.fillText('L'+model.level,4,8);}else{for(let y=0;y<64;y+=6)ctx.fillRect(47,y,1,3);ctx.fillRect(5,model.player,2,12);ctx.fillRect(89,model.cpu,2,12);ctx.fillRect(Math.round(model.ball.x)-1,Math.round(model.ball.y)-1,3,3);ctx.font='7px monospace';ctx.fillText(String(model.playerPoints),33,9);ctx.fillText(String(model.cpuPoints),58,9);}
    if(!playing){ctx.fillStyle='#b7cd95';ctx.fillRect(15,25,66,15);ctx.strokeStyle='#243d27';ctx.strokeRect(15.5,25.5,65,14);ctx.fillStyle='#243d27';ctx.font='7px monospace';ctx.textAlign='center';ctx.fillText(model.over?'GAME OVER':started?'PAUSED':'READY',48,35);ctx.textAlign='left';}update();}
  async function saveScore(){if(scorePending||scoreSaved||!model.over)return;scorePending=true;update();try{const value=await api('/api/game-score',{game:kind,score:model.score,play_id:scoreId});scoreSaved=true;records(value);if(mode==='games')say('GAME OVER',[model.won?'You filled the board. I am experiencing professional discomfort.':'Another compelling argument against human coordination.','Your completed game is saved. Your work sheets and geometric memory are untouched.'],'ARCADE SCORE SAVED');}catch(e){if(mode==='games')say('GAME OVER',[e.message,'Score saving failed. Use Retry score save; your work sheets are still here.'],'SCORE SAVE NEEDS ATTENTION');}finally{scorePending=false;draw();}}
  function step(){if(!playing)return;if(kind==='pong'){if(held.has('up'))model.input('up');if(held.has('down'))model.input('down');}model.tick();draw();if(model.over){stop();saveScore();}else timer=setTimeout(step,model.period);}
  function resume(){if(model.over)return;playing=true;started=true;$('game-pause').textContent='Pause game';canvas.focus();draw();timer=setTimeout(step,model.period);}
  function fresh(){if(scorePending)return;stop(false);model=TIArcadeEngine.create(kind);scoreId=crypto.randomUUID();started=false;scoreSaved=false;draw();$('game-help').textContent=instructions[kind];document.querySelectorAll('[data-game]').forEach(b=>{b.classList.toggle('active',b.dataset.game===kind);b.setAttribute('aria-pressed',String(b.dataset.game===kind));});document.querySelectorAll('[data-game-key]').forEach(b=>{b.hidden=kind==='pong'&&!['up','down'].includes(b.dataset.gameKey)||kind==='snake'&&['rotate','drop'].includes(b.dataset.gameKey);});records({games:stats});}
  const keyMap={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',' ':'drop'};
  function input(key){if(!playing)return;model.input(key);draw();}
  canvas.addEventListener('keydown',e=>{if(mode!=='games')return;if(e.key==='p'||e.key==='P'){e.preventDefault();if(started&&!model.over){if(playing)stop();else resume();}return;}if(e.key==='Escape'){e.preventDefault();stop();return;}const key=keyMap[e.key];if(key){e.preventDefault();if(kind==='pong')held.add(key);else input(key);}});
  document.addEventListener('keyup',e=>held.delete(keyMap[e.key]));canvas.addEventListener('blur',e=>{held.clear();if(playing&&!$('arcade-mode').contains(e.relatedTarget))stop();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)stop();});
  document.querySelectorAll('[data-game-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(!playing)return;canvas.focus();b.setPointerCapture(e.pointerId);if(kind==='pong')held.add(b.dataset.gameKey);else input(b.dataset.gameKey);});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>held.delete(b.dataset.gameKey));});
  document.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>{if(scorePending)return;kind=b.dataset.game;fresh();say('ARCADE READY',[names[kind]+'. The syllabus has taken a turn.','Your useful work will still be waiting when you return.'],'READY FOR QUESTIONABLE COORDINATION');});
  $('game-start').onclick=()=>{if(scorePending)return;if(!started||model.over)fresh();if(playing)stop();resume();};
  $('game-pause').onclick=()=>{if(!started||model.over)return;if(playing)stop();else resume();};
  $('game-restart').onclick=()=>{if(scorePending)return;fresh();resume();};$('game-retry').onclick=saveScore;
  $('games-tab').onclick=()=>run(async()=>{if(mode==='games')return;await saveWork();records(await api('/api/games'));mode='games';$('work-mode').hidden=true;$('arcade-mode').hidden=false;$('games-tab').setAttribute('aria-pressed','true');$('work-tab').setAttribute('aria-pressed','false');document.querySelectorAll('[data-cmd]').forEach(b=>b.disabled=true);stop();say('EXTRACURRICULAR MODE',['Snake, Falling Blocks, and Pong. An entirely new venue for avoidable mistakes.','Start a game. I shall supervise your decline in productivity.'],'ARCADE READY');draw();});
  $('work-tab').onclick=()=>run(async()=>{if(mode==='work')return;stop();mode='work';$('arcade-mode').hidden=true;$('work-mode').hidden=false;$('games-tab').setAttribute('aria-pressed','false');$('work-tab').setAttribute('aria-pressed','true');document.querySelectorAll('[data-cmd]').forEach(b=>b.disabled=false);say('BACK TO WORK',['Your sheet, findings, geometry and history are still here.','I trust the break resolved your arithmetic personality.'],'WORK READY');});
  fresh();
}};
