// SPDX-License-Identifier: AGPL-3.0-only
// Optional test dependency: npm install playwright && npx playwright install chromium
const { chromium } = require('playwright');
const { spawn } = require('node:child_process');
const path = require('node:path');
const fs = require('node:fs');

(async () => {
  const root=path.resolve(__dirname,'..');
  const state=process.env.TI_TEST_STATE || path.join(root,'browser-test.sqlite');
  const server=spawn(process.env.TI_PYTHON || 'python3',['-m','tiagi83','--state',state,'--port','8383','--backend','jax'],{cwd:root});
  let browser;
  try {
    await new Promise((resolve,reject)=>{server.stdout.on('data',d=>{if(d.toString().includes('http://'))resolve()});server.stderr.on('data',d=>process.stderr.write(d));server.once('exit',code=>reject(Error('Server exited '+code)));});
    let args=[];
    if(process.env.TI_CHROME_MODULE){const {default:c}=await import(process.env.TI_CHROME_MODULE);args=c.args;}
    browser=await chromium.launch({headless:true,args,...(process.env.TI_CHROME?{executablePath:process.env.TI_CHROME}:{})});
    const page=await browser.newPage({viewport:{width:1280,height:1100},acceptDownloads:true}),errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto('http://127.0.0.1:8383');await page.locator('#status').filter({hasText:'JAX BACKEND'}).waitFor();
    await page.getByRole('button',{name:'Audit sheet',exact:true}).click();await page.locator('#count').filter({hasText:'(1)'}).waitFor();
    await page.getByRole('button',{name:'Apply verified repairs',exact:true}).click();await page.locator('#status').filter({hasText:'WORK VERIFIED'}).waitFor();
    if(await page.getByRole('textbox',{name:'Row 2, Line total',exact:true}).inputValue()!=='32.00')throw Error('Repair failed');
    await page.getByRole('button',{name:'Restore sample as new sheet',exact:true}).click();await page.locator('#status').filter({hasText:'READY'}).waitFor();
    await page.getByRole('button',{name:'Audit sheet',exact:true}).click();await page.locator('#findings').filter({hasText:'Related incident #'}).waitFor();
    await page.getByRole('button',{name:'GRAPH',exact:true}).click();await page.locator('.graph-view').waitFor();if(await page.locator('.graph-cell').count()!==64)throw Error('Wrong geometry size');
    const out=process.env.TI_SCREENSHOT_DIR || root;
    await page.screenshot({path:path.join(out,'ti-agi83-desktop.png'),fullPage:true});
    await page.getByRole('button',{name:'TRACE',exact:true}).click();await page.locator('#status').filter({hasText:'LINEAGE RETAINED'}).waitFor();
    await page.getByRole('textbox',{name:'Row 1, Qty',exact:true}).fill('unknown');await page.getByRole('button',{name:'Audit sheet',exact:true}).click();await page.locator('#findings').filter({hasText:'plain bounded number'}).waitFor();
    await page.getByRole('button',{name:'Apply verified repairs',exact:true}).click();await page.locator('#status').filter({hasText:'HUMAN INPUT NEEDED'}).waitFor();
    if(await page.getByRole('textbox',{name:'Row 1, Qty',exact:true}).inputValue()!=='unknown')throw Error('Invented a value');
    const dlPromise=page.waitForEvent('download');await page.locator('[data-cmd="export"]').click();const dl=await dlPromise;if(!dl.suggestedFilename().endsWith('.csv'))throw Error('No CSV');
    await page.reload();await page.locator('#status').filter({hasText:'JAX BACKEND'}).waitFor();
    await page.getByRole('button',{name:'invoice sample copy',exact:true}).click();await page.locator('#status').filter({hasText:'AWAITING HUMAN ERROR'}).waitFor();if(await page.getByRole('textbox',{name:'Row 1, Qty',exact:true}).inputValue()!=='unknown')throw Error('Restart lost edits');
    await page.locator('#csv-file').setInputFiles({name:'browser-import.csv',mimeType:'text/csv',buffer:Buffer.from('Item,Qty,Unit price,Line total\nImported cable,5,8,41\n')});await page.locator('#status').filter({hasText:'READY FOR AUDIT'}).waitFor();
    await page.getByRole('button',{name:'Audit sheet',exact:true}).click();await page.locator('#count').filter({hasText:'(1)'}).waitFor();
    await page.getByRole('button',{name:'Apply verified repairs',exact:true}).click();await page.locator('#status').filter({hasText:'WORK VERIFIED'}).waitFor();
    if(await page.getByRole('textbox',{name:'Row 1, Line total',exact:true}).inputValue()!=='40.00')throw Error('Imported repair failed');
    await page.locator('#undo').click();await page.locator('#status').filter({hasText:'HISTORY PRESERVED'}).waitFor();
    if(await page.getByRole('textbox',{name:'Row 1, Line total',exact:true}).inputValue()!=='41')throw Error('Undo lost imported original');
    await page.locator('#receipt').click();await page.locator('#status').filter({hasText:'LOCAL INTEGRITY PASS'}).waitFor();
    const historyPromise=page.waitForEvent('download');await page.locator('#backup').click();const history=await historyPromise;
    if(history.suggestedFilename()!=='ti-agi83-history.json')throw Error('No history export');
    const beforeGames=await page.evaluate(()=>fetch('/api/export').then(r=>r.json()));
    await page.locator('#games-tab').click();await page.locator('#status').filter({hasText:'ARCADE READY'}).waitFor();
    let failScoreOnce=true;await page.route('**/api/game-score',async route=>{if(failScoreOnce){failScoreOnce=false;await route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Simulated temporary score failure'})});}else await route.continue();});
    await page.locator('#game-start').click();await page.locator('#game-state').filter({hasText:'PLAYING'}).waitFor();
    await page.locator('#game-pause').click();await page.locator('#game-state').filter({hasText:'PAUSED'}).waitFor();
    await page.locator('#game-pause').click();await page.locator('#game-state').filter({hasText:'PLAYING'}).waitFor();
    await page.locator('#status').filter({hasText:'SCORE SAVE NEEDS ATTENTION'}).waitFor();
    await page.locator('#game-retry').click();await page.locator('#game-state').filter({hasText:'SCORE SAVED'}).waitFor();
    const firstScores=await page.evaluate(()=>fetch('/api/games').then(r=>r.json()));
    if(firstScores.games.snake.plays!==1)throw Error('Completed Snake score not saved exactly once');
    await page.locator('[data-game="blocks"]').click();await page.locator('#game-start').click();
    await page.locator('#game-canvas').press('Space');
    if(await page.locator('#game-score').textContent()==='Score 0 · Lines 0 · Level 1')throw Error('Blocks hard drop failed');
    await page.locator('#work-tab').click();await page.locator('#status').filter({hasText:'WORK READY'}).waitFor();
    if(await page.getByRole('textbox',{name:'Row 1, Line total',exact:true}).inputValue()!=='41')throw Error('Game switch lost sheet');
    const afterGames=await page.evaluate(()=>fetch('/api/export').then(r=>r.json()));
    for(const key of ['sheets','geometry','incidents','audits'])if(JSON.stringify(afterGames[key])!==JSON.stringify(beforeGames[key]))throw Error('Games changed '+key);
    if(afterGames.game_scores.length!==1)throw Error('History export lacks completed score');
    await page.reload();await page.locator('#status').filter({hasText:'JAX BACKEND'}).waitFor();
    await page.locator('#games-tab').click();await page.locator('#game-best').filter({hasText:'1 completed game'}).waitFor();
    await page.locator('[data-game="pong"]').click();await page.locator('#game-start').click();
    await page.locator('#game-canvas').press('ArrowUp');await page.locator('#game-pause').click();
    await page.locator('#game-state').filter({hasText:'PAUSED'}).waitFor();
    await page.locator('[data-game="blocks"]').click();await page.locator('#game-start').click();
    await page.locator('[data-game-key="drop"]').click();await page.locator('#game-pause').click();
    if(await page.locator('#game-score').textContent()==='Score 0 · Lines 0 · Level 1')throw Error('Touch hard drop failed');
    await page.screenshot({path:path.join(out,'ti-agi83-arcade-desktop.png'),fullPage:true});
    await page.setViewportSize({width:390,height:844});
    const width=await page.evaluate(()=>document.documentElement.scrollWidth);if(width>390)throw Error('Mobile layout overflows: '+width);
    await page.screenshot({path:path.join(out,'ti-agi83-mobile.png'),fullPage:true});
    await page.locator('#game-pause').click();await page.locator('[data-game-key="drop"]').click();await page.locator('#game-pause').click();
    await page.screenshot({path:path.join(out,'ti-agi83-arcade-mobile.png'),fullPage:true});
    if(errors.length)throw Error(errors.join(';'));
    console.log(JSON.stringify({status:'PASS',backend:'JAX',verifiedRepair:'32.00',relatedIncident:true,graphCells:64,trace:true,unknownPreserved:true,csv:dl.suggestedFilename(),reloadPreserved:true,csvImportRepair:'40.00',undo:true,receipts:true,historyExport:true,mobileWidth:width,arcade:{games:3,keyboard:true,touch:true,pauseResume:true,scoreRestart:true,scoreRetry:true,workIsolation:true},pageErrors:errors}));
  } catch(e) {if(browser){const pages=browser.contexts().flatMap(c=>c.pages());for(const p of pages)console.error(await p.locator('#screen-body').textContent(),await p.locator('#game-state').textContent());}throw e;} finally {if(browser)await browser.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
